### PR TITLE
DO NOT MERGE Update runtime to 24.08

### LINKED ISSUE #88: Update to 24.08
An update would be appreciated.

If you need some help I can work on a pr  ^^.

### PR DESCRIPTION
**Pull request by hfiguiere**
Use llvm18
Update ldc-cycle to 1.39

Will create the branch

Will close #88

### CODE REVIEW

**Comment by Erick555** [comment]
this misses metainfo update.

**Comment by hfiguiere** [comment]
Updated.

**Comment by hfiguiere** [comment]
tested with a real case. WFM.

**Comment by hfiguiere** [comment]
created branch

**Pull request closed without merging**
